### PR TITLE
Add how-to video and example component to init

### PR DESCRIPTION
**Pull request by decepulis**
> ⚠️ draft until the get started video is ready. For now, we're using a placeholder.

## Why?
It would be good to provide users with next steps at the end of `npx next-video init`. 
To start, maybe we can provide users with a test video so they can immediately start playing with the component.

## What's new?
1. Writes `videos/.getStarted.mp4.json` at the same time that `videos/.gitignore` is written.
2. Provides an example component at the end of the `init` flow

## What it looks like
cli output after this PR

### CODE REVIEW

**Review by luwes — APPROVED** [review]
LGTM 👍

**Comment by heff** [comment]
Yeah, I like this a lot. Looks good to merge.

How hard would it be to just create a page for them in their app? If we can I think we could do a lot with that.

**Comment by heff** [comment]
We should still merge this, right?

**Comment by decepulis** [comment]
@heff yeah I think it's good to go. I put the real get started video in there.

**Pull request merged**
